#!/bin/sh

# This shim provides defaults when tmux is started without arguments,
# which is the case when using tmux from VSCode for example.
#
# Session name is set to working directory's basename.
# If a session already exists, it's attached to, otherwise it's created.

if [ -z "${NOSHIM_tmux}" ]; then
  echo "tmux: command not found"
  exit 1
fi

if [ $# -eq 0 ]; then
  SESSION=$(echo ${PWD##*/} | tr . _)
  $NOSHIM_tmux new-session -s $SESSION 2>/dev/null || $NOSHIM_tmux attach-session -d -t $SESSION
else
  $NOSHIM_tmux "$@"
fi
