#!/usr/bin/env bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install \
  asdf autoconf automake coreutils curl difftastic git gh gnu-tar gpg jq \
  libtool libxslt libyaml openssl readline tig tmux unixodbc \
  unzip vim watch watchman watchexec zsh

if [[ $(uname) == "Darwin" ]]; then
  brew install --cask 1password-cli
  brew install --cask ghostty
  brew install --cask google-cloud-sdk
  brew install --cask nikitabobko/tap/aerospace
fi
