#!/usr/bin/env bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install \
  autoconf automake coreutils curl git \
  libtool libxslt libyaml openssl readline unixodbc \
  unzip vim watch watchman zsh
